name: test
on:
  push:
    branches: ['*']
  pull_request:
jobs:
  use-action:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, windows-2022, windows-2019, windows-2016]
    steps:
      - uses: actions/checkout@v2
      - uses: ./
      - uses: ./
        with:
          winsdk-build-version: 19041
