name: test
on:
  push:
    branches: ['*']
  pull_request:
jobs:
  win-latest:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
      - uses: ./
        with:
          winsdk-build-version: 19041
