name: version
on:
  workflow_dispatch:
    inputs:
      type:
        description: 'Release Type'
        required: true
        default: 'minor'
jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set Git user
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm version ${{ github.event.inputs.type }}
      - name: Determine release branch
        id: var
        run: echo ::set-output name=branch::"v$(npm -s run env echo '$npm_package_version' | sed 's/\([0-9]*\).*/\1/')"
      - name: Create or update release branch
        run: |
          git show-branch $BRANCH &>/dev/null && git checkout $BRANCH || git checkout -b $BRANCH
          git merge --ff-only ${GITHUB_REF#refs/heads/}
        env:
          BRANCH: ${{ steps.var.outputs.branch }}
      - run: git push --all --follow-tags
