name: version
on:
  workflow_dispatch:
    inputs:
      type:
        description: 'Release Type'
        required: true
        default: 'minor'
jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}
      - name: Set Git user
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm version ${{ github.event.inputs.type }}
      - run: echo "VERSION=$(npm pkg get version --workspaces=false | xargs)" >> $GITHUB_ENV
      - name: Create or update release branch
        run: |
          git show-branch v${VERSION%%.*} &>/dev/null && git checkout v${VERSION%%.*} || git checkout -b v${VERSION%%.*}
          git merge --ff-only ${GITHUB_REF#refs/heads/}
      - run: git push --all --follow-tags
      - run: gh release create v$VERSION --generate-notes -t $VERSION
        env:
          GH_TOKEN: ${{ github.token }}
